---
title: "Gov 50 Final Project"
author: "Zachary Mecca"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Do people making more money commute further to work? In this study, I will look at data from my hometown of Buffalo, NY in order to investigate this question. I hypothesize that higher incomes will cause people to choose to live further away from their jobs, and therefor, have longer commute times. I hypothesize this because it is very clear that there is high income disparities between the city of Buffalo (where most jobs are) and the surrounding suburbs. I want to test if these high-income earners are living in the suburbs then commuting into the city to work, and if there is a relationship between higher income and further commute, or if higher income people choose to live in the suburbs where they have high paying jobs, where they would have a shorter commute. The data I will be using comes from two different datasets that I will have to merge based on geography. The explanatory variable will be income, as this will give people greater ability to live in high-income areas with high property value. This is measured in $ per year. The outcome variable of interest is commute time. This is measured in minutes. The pattern that would support my hypothesis is that greater income leads to greater commute time. Something disproving my hypothesis would be no correlation between the two variables. In the case of a negative relationship, that would disprove my hypothesis by proving the opposite, that higher income people are able to commute shorter times by living closer to their high-income jobs.


## Data Visualization
```{r}
library(tidyverse)
commute <- read_csv("data/commute.csv")
income <- read_csv("data/income.csv")

commute |>
  group_by(Geography) |>
  ggplot(mapping = aes(
    x = Average_Commute_Time
  )) +
  geom_histogram() +
  labs(title = "Distribution of Commute Times in Buffalo, NY",
       x = "Average Commute Time",
       y = "Number of Commuters")

income |>
  group_by(Year) |>
  mutate(year_mean = mean(Household_Income)) |>
  ggplot(mapping = aes(
    x = Year,
    y = year_mean
  )) +
  geom_point()
```
From these graphs it can be seen that there is on average about a 20 minute commute time in the Buffalo area, with a small proportion of commuters with times greater than 25 or 30 minutes. As seen from the income data, average income in the Buffalo area has gone up over time. Now that we know about commute times and income over time, we can begin to do statistical analysis on the effects these have on each other using bootstrapping and other techniques. 

